package lexer;

public enum StateCode {
    BLANK,
    IDENT_READING,
    LINE_COMMENT_READING, CROSSLINE_COMMENT_READING,
    CROSSLINE_COMMENT_STAR_END, CROSSLINE_COMMENT_END,
    FORMATSTRING_READING, FORMATSTRING_END,
    FORMATSRING_PER, FORMATSTRING_RESLASH,
    NUMBER,
    PLUS, MINU, MULT, DIV_COMMENTSLASH, MOD,
    LESS, LESS_AND_EQUAL,
    GREAT, GREAT_AND_EQUAL,
    ASSIGN_EQUAL1, EQUAL2,
    NOT, NOT_EQUAL,
    AND_1, AND_2,
    OR_1, OR_2,
    SEMI, COMMA,
    LPARENT, RPARENT,
    LBRACK, RBRACK,
    LBRACE, RBRACE,
    WRONG
}