package parser.component;

public enum CompType {
    WORD,
    IDENT,
    COMP_UNIT,
    DECL, FUNC_DEF, MAIN_FUNC_DEF,
    CONST_DECL, VAR_DECL,
    CONST_DEF, CONST_EXP, CONST_INIT_VAL,
    VAR_DEF,
    FUNC_TYPE, FUNC_F_PARAMS, FUNC_F_PARAM,
    FUNC_R_PARAMS,
    ADD_EXP, MUL_EXP, UNARY_EXP, UNARY_OP,
    EXP, PRIMARY_EXP, LVAL, NUMBER, INT_CONST,
    BTYPE,
    BLOCK, BLOCK_ITEM,
    STMT,
    COND, LOR_EXP, LAND_EXP, EQ_EXP, REL_EXP,
    FOR_STMT,
    FORMAT_STRING, INIT_VAL
}
